name: ocs-advanced-binder
channels:
  - conda-forge
dependencies:
  - python=3.12
  - ipykernel=6.29
  - xarray=2024.10
  - zarr=2.18
  - rioxarray=0.17
  - geopandas=1.0
  - shapely=2.0
  - numpy=2.0
  - pandas=2.2
  - matplotlib=3.9
  - holoviews=1.19
  - cartopy=0.24
  - hvplot=0.11
  - geoviews=1.13
  - scikit-learn=1.5
  - xgboost=2.1
  - s3fs=2024.10
  - dask=2024.10
  - xvec=0.3
  - pystac-client=0.8
  - intake-esm=2023.11
  - stackstac=0.5
  - fsspec=2024.10
  - requests=2.32
  - metpy=1.7
  - boto3=1.40
  - pip=26.0
  - pip:
    - lexcube=1.0